<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<!DOCTYPE manufacturing-processes [
	<!ELEMENT manufacturing-processes (process*, salvage*)>
	<!ELEMENT process (description?, inputs, outputs)>
	<!ATTLIST process name CDATA #REQUIRED>
	<!ATTLIST process tech CDATA #REQUIRED>
	<!ATTLIST process skill CDATA #REQUIRED>
	<!ATTLIST process work-time CDATA #REQUIRED>
	<!ATTLIST process process-time CDATA #REQUIRED>
	<!ATTLIST process power-required CDATA #REQUIRED>
	<!ELEMENT description (#PCDATA)>
	<!ELEMENT inputs (resource*, part*)>
	<!ELEMENT outputs (resource*, part*, equipment*, vehicle*)>
	<!ELEMENT resource EMPTY>
	<!ATTLIST resource name CDATA #REQUIRED>
	<!ATTLIST resource amount CDATA #REQUIRED>
	<!ELEMENT part EMPTY>
	<!ATTLIST part name CDATA #REQUIRED>
	<!ATTLIST part number CDATA #REQUIRED>
	<!ELEMENT equipment EMPTY>
	<!ATTLIST equipment name CDATA #REQUIRED>
	<!ATTLIST equipment number CDATA #REQUIRED>
	<!ELEMENT vehicle EMPTY>
	<!ATTLIST vehicle name CDATA #REQUIRED>
	<!ATTLIST vehicle number CDATA #REQUIRED>
	<!ELEMENT salvage (part-salvage*)>
	<!ATTLIST salvage item-name CDATA #REQUIRED>
	<!ATTLIST salvage type (equipment|vehicle) #REQUIRED>
	<!ATTLIST salvage tech CDATA #REQUIRED>
	<!ATTLIST salvage skill CDATA #REQUIRED>
	<!ATTLIST salvage work-time CDATA #REQUIRED>
	<!ELEMENT part-salvage EMPTY>
	<!ATTLIST part-salvage name CDATA #REQUIRED>
	<!ATTLIST part-salvage number CDATA #REQUIRED>
]>

<!--
1. A Chemical Approach to C02 Util on Mars
http://www.uapress.arizona.edu/onlinebks/ResourcesNearEarthSpace/resources28.pdf

2. Regolith composition :
http://canada.marssociety.org/winnipeg/soil.html
 -->

<!-- List of all manufacturing processes. -->
<manufacturing-processes>


<!-- 
 work-time means the amount of time it takes for settlers to examine, operate and direct this process.
 process-time means the amount of time it takes for the output resource to be synthesized.
-->
	
<!--
	Note: In earth's ocean, the most common compound found in brine water are magnesium chloride, magnesium sulfate,
	calcium sulfate, potassium chloride, magnesium bromide, and calcium carbonate.
-->
	<!-- Purify Rock Salt to Food Grade Table Salt -->
	<process name="purify rock salt into table/epsom salt and other compounds"
	tech="1" skill="1" work-time="10.0" process-time="10"
			power-required=".4">
		<description> http://www.madehow.com/Volume-2/Salt.html
			One method of evaporating brine is solar evaporation.
			Most brine is processed by a multiple-effect vacuum evaporator.
			This device consists of three or more closed metal cylinders with conical bottoms.
			Brine is first treated chemically to remove calcium and magnesium compounds.
			It then fills the bottom.
			Brine may also be processed in a grainer.
		</description>
		<inputs>
			<resource name="rock salt" amount="10.0" />
		</inputs>
		<outputs>
			<!--TODO: need research to determine the average amount-->
			<resource name="table salt" amount="4" />
			<resource name="calcium" amount="0.5" />
			<resource name="magnesium" amount="0.5" />
			<resource name="potassium" amount="0.5" />
			<resource name="calcium carbonate" amount="0.5" />
			<resource name="epsom salt" amount="4" />
			<!--Epsom Salt is Magnesium Sulfate-->
		</outputs>
	</process>

	<process name="make pulp from cane fiber and crop waste"
			tech="2" skill="0"
			work-time="50"
			process-time="300"
			power-required=".1">
		<inputs>
			<resource name="cane fiber" amount="2.5" />
			<resource name="crop waste" amount="2.5" />
			<resource name="water" amount="1" />
		</inputs>
		<outputs>
			<resource name="pulp" amount="5.5" />
			<resource name="grey water" amount=".4" />
			<resource name="solid waste" amount=".1" />
		</outputs>
	</process>

	<process name="make pulp from cane fiber and crop waste (large batch)"
			tech="2" skill="2"
			work-time="200"
			process-time="800"
			power-required=".5">
		<inputs>
			<resource name="cane fiber" amount="25" />
			<resource name="crop waste" amount="25" />
			<resource name="water" amount="10" />
		</inputs>
		<outputs>
			<resource name="pulp" amount="55" />
			<resource name="grey water" amount="4" />
			<resource name="solid waste" amount="1" />
		</outputs>
	</process>

	<process name="make paper, napkin and toilet tissue from pulp"
			tech="1" skill="1"
			work-time="50"
			process-time="100"
			power-required=".1">
		<inputs>
			<resource name="pulp" amount="5" />
			<resource name="bleaching chemical" amount=".05" />
		</inputs>
		<outputs>
			<resource name="paper" amount="1" />
			<resource name="napkin" amount="2" />
			<resource name="toilet tissue" amount="2" />
		</outputs>
	</process>

	<process name="make paper, napkin and toilet tissue from pulp (large batch)"
			tech="1" skill="1"
			work-time="150"
			process-time="500"
			power-required=".5">
		<inputs>
			<resource name="pulp" amount="50" />
			<resource name="bleaching chemical" amount=".5" />
		</inputs>
		<outputs>
			<resource name="paper" amount="10" />
			<resource name="napkin" amount="20" />
			<resource name="toilet tissue" amount="20" />
		</outputs>
	</process>

	<!-- http://www.paperonweb.com/chemical.htm
		CHEMICALS USED IN PULP &PAPER MANUFACTURING AND COATING
		Over 3000 different types of chemicals "can be used" in papermaking, in practice only about 200 individual chemicals
		 are typically used, each satisfying a specific need.
TODO 1: need to check the amount needed
TODO 2: need to recruit chemist to monitor the process
		 -->
	<process name="make bleaching chemical for paper making"
			tech="2" skill="1"
			work-time="10"
			process-time="50"
			power-required=".05">
		<inputs>
			<resource name="oxygen" amount=".2" />
			<resource name="sulfur" amount=".05" />
			<resource name="ammonia" amount=".05" />
			<resource name="sodium hypochlorite" amount=".05" />
			<resource name="calcium carbonate" amount=".1" />
			<resource name="magnesium" amount=".05" />
		</inputs>
		<outputs>
			<resource name="bleaching chemical" amount=".5" />
		</outputs>
	</process>

	<process name="make bleaching chemical for paper making (large batch)"
			tech="2" skill="1"
			work-time="50"
			process-time="200"
			power-required=".3">
		<inputs>
			<resource name="oxygen" amount="2" />
			<resource name="sulfur" amount=".5" />
			<resource name="ammonia" amount=".5" />
			<resource name="sodium hypochlorite" amount=".5" />
			<resource name="calcium carbonate" amount="1" />
			<resource name="magnesium" amount=".5" />
		</inputs>
		<outputs>
			<resource name="bleaching chemical" amount="5" />
		</outputs>
	</process>


<!-- https://en.wiki2.org/wiki/Electrochlorination
		NaCl + H2O + ENERGY â†’ NaOCl + H2 energy is added to sodium chloride (table salt) in water, resulting in sodium hypochlorite and hydrogen gas.
TODO: need to recruit chemist to monitor the process
Note: 1 kg of H2 is 14.13 liter

-->
	<process name="make sodium hypochlorite for bleaching and sanitation"
			tech="2" skill="1"
			work-time="10"
			process-time="100"
			power-required=".1">
		<inputs>
			<resource name="table salt" amount="5.85" />
			<resource name="water" amount="1.8" />

		</inputs>
		<outputs>
			<resource name="sodium hypochlorite" amount="7.45" />
			<resource name="hydrogen" amount=".2" />
		</outputs>
	</process>

	<process name="make sodium hypochlorite for bleaching and sanitation (large batch)"
			tech="2" skill="1"
			work-time="50"
			process-time="400"
			power-required=".5">
		<inputs>
			<resource name="table salt" amount="58.5" />
			<resource name="water" amount="18" />

		</inputs>
		<outputs>
			<resource name="sodium hypochlorite" amount="74.5" />
			<resource name="hydrogen" amount="2" />
		</outputs>
	</process>

	<process name="make fertilizers for growing crops"
			tech="2" skill="2"
			work-time="25"
			process-time="250"
			power-required="0.2">
		<inputs>
		<!-- TODO:
		1. Chemists may tweak the input amount and the yield
		2. Arbitrary figures are used. Need research
		-->
			<resource name="methane" amount="1" />
			<resource name="hydrogen" amount="0.5" />
			<resource name="nitrogen" amount="0.5" />
			<resource name="nitrate" amount="1" />
			<resource name="nitrite" amount="0.5" />
			<resource name="ammonia" amount="2" />
			<resource name="potassium" amount="0.5" />
			<resource name="phosphorus" amount="0.5" />
			<resource name="zinc" amount="0.02" />
			<resource name="calcium" amount="0.02" />
			<resource name="sulfur" amount="0.02" />
			<resource name="magnesium" amount="0.02" />
			<resource name="iron powder" amount="0.02" />
		</inputs>
		<outputs>
			<resource name="Fertilizer" amount="7.0" />
		</outputs>
	</process>

	<process name="make fertilizers for growing crops (large batch)"
			tech="2" skill="2"
			work-time="50"
			process-time="500"
			power-required="1">
		<inputs>
		<!-- TODO:
		1. Chemists may tweak the input amount and the yield
		2. Arbitrary figures are used. Need research
		-->
			<resource name="methane" amount="10" />
			<resource name="hydrogen" amount="5" />
			<resource name="nitrogen" amount="5" />
			<resource name="nitrate" amount="10" />
			<resource name="nitrite" amount="5" />
			<resource name="ammonia" amount="20" />
			<resource name="potassium" amount="5" />
			<resource name="phosphorus" amount="5" />
			<resource name="zinc" amount="0.2" />
			<resource name="calcium" amount="0.2" />
			<resource name="sulfur" amount="0.2" />
			<resource name="magnesium" amount="0.2" />
			<resource name="iron powder" amount="0.2" />
		</inputs>
		<outputs>
			<resource name="Fertilizer" amount="70.0" />
		</outputs>
	</process>

<!--	DISABLE THIS PROCESS AND USE IRON POWDER INSTEAD OF IRON
        ALSO IRON POWDER IS PRODUCED IN TWO PROCESSES ALREADY
	<process name="extract iron from iron oxide"
			tech="2" skill="2"
			work-time="100"
			process-time="300"
			power-required="3.0">
		<inputs>
			<resource name="Iron Oxide" amount="5.0" />
			<resource name="Carbon" amount="5.0" />
		</inputs>
		<outputs>
			<resource name="Iron" amount="7.0" />
			<resource name="Carbon Monoxide" amount="3.0" />
		</outputs>
	</process>
	 TODO: Need to find the real molecular mass of the initial and resulting product
			Fe2O3 + 3C â†’ 2Fe + 3CO
-->

	<process name="do carbon monoxide iron reduction"
			tech="1" skill="1"
			work-time="50"
			process-time="200"
			power-required=".2">
		<description>Fe&lt;sub&gt;2&lt;/sub&gt;O&lt;sub&gt;3&lt;/sub&gt; + 3CO -> 2Fe + 3CO&lt;sub&gt;2&lt;/sub&gt;</description>
		<inputs>
			<resource name="iron oxide" amount="50.0" />
			<resource name="carbon monoxide" amount="26.4" />
		</inputs>
		<outputs>
			<resource name="iron powder" amount="34.9" />
			<resource name="carbon dioxide" amount="41.3" />
		</outputs>
	</process>

	<process name="do carbon monoxide iron reduction (large batch)"
			tech="1" skill="2"
			work-time="250"
			process-time="1000"
			power-required="1.0">
		<description>Fe&lt;sub&gt;2&lt;/sub&gt;O&lt;sub&gt;3&lt;/sub&gt; + 3CO -> 2Fe + 3CO&lt;sub&gt;2&lt;/sub&gt;</description>
		<inputs>
			<resource name="iron oxide" amount="500.0" />
			<resource name="carbon monoxide" amount="264.0" />
		</inputs>
		<outputs>
			<resource name="iron powder" amount="349.0" />
			<resource name="carbon dioxide" amount="413.0" />
		</outputs>
	</process>

	<process name="do hydrogen iron reduction"
			tech="1" skill="1"
			work-time="50"
			process-time="200"
			power-required=".2">
		<description>Fe&lt;sub&gt;2&lt;/sub&gt;O&lt;sub&gt;3&lt;/sub&gt; + 3H&lt;sub&gt;2&lt;/sub&gt;
		-> 2Fe + 3H&lt;sub&gt;2&lt;/sub&gt;O</description>
		<inputs>
			<resource name="iron oxide" amount="50.0" />
			<resource name="hydrogen" amount="2.5" />
		</inputs>
		<outputs>
			<resource name="iron powder" amount="34.9" />
			<resource name="grey water" amount="16.9" />
		</outputs>
	</process>

	<process name="do hydrogen iron reduction (large batch)"
			tech="1" skill="2"
			work-time="250"
			process-time="1000"
			power-required="1">
		<description>Fe&lt;sub&gt;2&lt;/sub&gt;O&lt;sub&gt;3&lt;/sub&gt; + 3H&lt;sub&gt;2&lt;/sub&gt;
		-> 2Fe + 3H&lt;sub&gt;2&lt;/sub&gt;O</description>
		<inputs>
			<resource name="iron oxide" amount="500.0" />
			<resource name="hydrogen" amount="25.0" />
		</inputs>
		<outputs>
			<resource name="iron powder" amount="349.0" />
			<resource name="grey water" amount="169.0" />
		</outputs>
	</process>

	<!-- Produces 5x 5kg iron ingots. -->
	<process name="cast iron ingot" tech="2" skill="1" work-time="50" process-time="200"
			power-required=".2">
		<inputs>
			<resource name="iron powder" amount="35.0" />
		</inputs>
		<outputs>
			<part name="iron ingot" number="5" />
		</outputs>
	</process>

	<!-- Produces 50x 5kg iron ingots. -->
	<process name="cast iron ingot (large batch)" tech="2" skill="2" work-time="150" process-time="600"
			power-required="1.0">
		<inputs>
			<resource name="iron powder" amount="350.0" />
		</inputs>
		<outputs>
			<part name="iron ingot" number="50" />
		</outputs>
	</process>

	<!-- Produces 1m x 1m x 1mm (7.85kg) sheet of iron. -->
	<process name="make iron sheet" tech="2" skill="2" work-time="50" process-time="200"
			power-required=".5">
		<inputs>
			<resource name="iron powder" amount="15.7" />
		</inputs>
		<outputs>
			<part name="iron sheet" number="2" />
		</outputs>
	</process>

	<!-- Produces 1m x 1m x 1mm (7.85kg) sheet of iron. -->
	<process name="roll iron sheet" tech="2" skill="2" work-time="50" process-time="200"
			power-required=".5">
		<inputs>
			<part name="iron ingot" number="8" />
		</inputs>
		<outputs>
			<resource name="iron powder" amount="1.05" />		
			<part name="iron sheet" number="7" />	
		</outputs>
	</process>

	<!-- Produces one 5kg aluminum ingots. -->
	<process name="cast aluminum ingot"
			tech="1" skill="1"
			work-time="50"
			process-time="50"
			power-required=".2">
		<description>Al&lt;sub&gt;2&lt;/sub&gt;O&lt;sub&gt;3&lt;/sub&gt; + 3C -> 2Al + 3CO; 
		1 mole - Al2CO3: 101.96g; 3C: 36g; 2Al: 54g; 3CO: 64g</description>
		<inputs>
			<resource name="aluminum oxide" amount="9.44" />
			<resource name="carbon" amount="3.33" />
		</inputs>
		<outputs>
			<resource name="carbon monoxide" amount="7.78" />
			<part name="aluminum ingot" number="1" />
		</outputs>
	</process>

	<!-- Produces 50x 1kg aluminum ingots. -->
	<process name="cast aluminum ingot (large batch)" tech="1" skill="1" work-time="250" process-time="250"
			power-required="1">
		<description>Al&lt;sub&gt;2&lt;/sub&gt;O&lt;sub&gt;3&lt;/sub&gt; + 3C -> 2Al + 3CO</description>
		<inputs>
			<resource name="aluminum oxide" amount="94.4" />
			<resource name="carbon" amount="33.3" />
		</inputs>
		<outputs>
			<resource name="carbon monoxide" amount="77.8" />
			<part name="aluminum ingot" number="10" />
		</outputs>
	</process>

	<!-- Produces 1m x 2m x 1mm (5kg) sheet of aluminum. -->
	<process name="make aluminum sheet" tech="1" skill="1" work-time="50" process-time="20"
			power-required=".7">
		<description>Al&lt;sub&gt;2&lt;/sub&gt;O&lt;sub&gt;3&lt;/sub&gt; + 3C -> 2Al + 3CO</description>
		<inputs>
			<resource name="aluminum oxide" amount="9.5" />
			<resource name="carbon" amount="3.0" />
		</inputs>
		<outputs>
			<resource name="carbon monoxide" amount="7.5" />
			<part name="aluminum sheet" number="1" />
		</outputs>
	</process>

	<!-- Produces 1m x 1m x 1mm (2.72kg) sheet of aluminum. Each Al ingot is 5kg-->
	<process name="roll aluminum sheet" tech="1" skill="1" work-time="50" process-time="20"
			power-required=".4">
		<inputs>
			<part name="aluminum ingot" number="2" />
		</inputs>
		<outputs>
			<resource name="aluminum oxide" amount="1.84" />
			<part name="aluminum sheet" number="3" />
		</outputs>
	</process>

	<process name="do pyrolyze reaction" tech="1" skill="1" work-time="25" process-time="20"
			power-required=".1">
		<description>CH&lt;sub&gt;4&lt;/sub&gt; -> C + 2H&lt;sub&gt;2&lt;/sub&gt;</description>
		<inputs>
			<resource name="methane" amount="1.3" />
		</inputs>
		<outputs>
			<resource name="carbon" amount="1.0" />
			<resource name="hydrogen" amount=".3" />
		</outputs>
	</process>

	<process name="do advanced pyrolyze reaction" tech="2" skill="2" work-time="50" process-time="40"
			power-required=".5">
		<description>CH&lt;sub&gt;4&lt;/sub&gt; -> C + 2H&lt;sub&gt;2&lt;/sub&gt;</description>
		<inputs>
			<resource name="methane" amount="13.0" />
		</inputs>
		<outputs>
			<resource name="carbon" amount="10.0" />
			<resource name="hydrogen" amount="3.0" />
		</outputs>
	</process>

	<!-- Produces 5 5kg steel ingots. -->
	<process name="do steel ingot alloying" tech="1" skill="1" work-time="10" process-time="20"
			power-required=".1">
		<inputs>
			<resource name="iron powder" amount="25.0" />
			<resource name="carbon" amount=".5" />
		</inputs>
		<outputs>
			<part name="steel ingot" number="5" />
		</outputs>
	</process>

	<!-- Produces 50 5kg steel ingots. -->
	<process name="do steel ingot alloying (large batch)" tech="1" skill="1" work-time="50" process-time="100"
			power-required=".5">
		<inputs>
			<resource name="iron powder" amount="250.0" />
			<resource name="carbon" amount="5.0" />
		</inputs>
		<outputs>
			<part name="steel ingot" number="50" />
		</outputs>
	</process>

	<!-- Produces 1m x `m x 1mm (7.8kg) sheet of steel. -->
	<process name="make steel sheet" tech="0" skill="0" work-time="50" process-time="10"
			power-required=".3">
		<inputs>
			<resource name="iron powder" amount="7.7" />
			<resource name="manganese" amount=".1" />			
			<resource name="carbon" amount=".1" />
		</inputs>
		<outputs>
			<part name="steel sheet" number="1" />
		</outputs>
	</process>

	<!-- Produces 1m x 1m x 1mm (7.8kg) sheet of steel. -->
	<process name="roll steel sheet" tech="0" skill="0" work-time="50" process-time="10"
			power-required=".3">
		<inputs>
			<resource name="manganese" amount=".1" />		
			<part name="steel ingot" number="8" />
		</inputs>
		<outputs>
			<resource name="iron powder" amount="1.0" />
			<part name="steel sheet" number="5" />
		</outputs>
	</process>

	<!-- Produces 0.05 kg spool of thick steel wire from 5 kg steel ingot. -->
	<process name="draw steel wire" tech="0" skill="0" work-time="50" process-time="20"
			power-required=".2">
		<inputs>
			<part name="steel ingot" number="1" />
		</inputs>
		<outputs>
			<part name="steel wire" number="100" />
		</outputs>
	</process>

	<!-- Produces 1kg of steel cable from 5kg steel ingot. -->
	<process name="do steel cable winding" tech="0" skill="0" work-time="50" process-time="20"
			power-required="0.1">
		<inputs>
			<part name="steel ingot" number="1" />
		</inputs>
		<outputs>
			<part name="steel cable" number="5" />
		</outputs>
	</process>

	<!-- Produces 8x 1m x 2mm x 20cm steel pipe. -->
	<process name="make steel pipe" tech="0" skill="0" work-time="50" process-time="20"
			power-required=".1">
		<inputs>
			<part name="steel sheet" number="1" />
		</inputs>
		<outputs>
			<resource name="iron powder" amount="0.8" />
			<part name="steel pipe" number="8" />
		</outputs>
	</process>

	<!-- Produces 8x 1m x 2mm x 20cm iron pipe. -->
	<process name="make iron pipe" tech="0" skill="0" work-time="50" process-time="20"
			power-required=".1">
		<inputs>
			<part name="iron sheet" number="1" />
		</inputs>
		<outputs>
			<resource name="iron powder" amount="0.8" />
			<part name="iron pipe" number="8" />
		</outputs>
	</process>

	<process name="make fire extinguisher" tech="2" skill="1" work-time="100" process-time="50"
			power-required="0.1">
		<inputs>
			<resource name="carbon dioxide" amount="10.0" />
			<part name="steel canister" number="1" />
			<part name="valve" number="2" />
			<part name="gasket" number="4" />
			<part name="plastic tubing" number="1" />
		</inputs>
		<outputs>
			<part name="fire extinguisher" number="1" />
		</outputs>
	</process>

	<process name="make steel valve" tech="2" skill="1" work-time="200" process-time="200"
			power-required="0.1">
		<inputs>
			<part name="steel ingot" number="1" />
		</inputs>
		<outputs>
			<part name="valve" number="25" />
		</outputs>
	</process>

	<!-- Using reinforced fiberglass wrapped in aluminum sheeting to make satellite dish. -->
	<process name="make satellite dish" tech="2" skill="3" work-time="200" process-time="200"
			power-required="0.4">
		<inputs>
			<resource name="polyester resin" amount=".5" />
			<resource name="styrene" amount=".5" />
			<part name="fiberglass" number="1" />		
			<part name="aluminum sheet" number="1" />
			<part name="electrical wire" number="3" />
			<part name="wire connector" number="4" />
			<part name="optical cable" number="2" />
		</inputs>
		<outputs>
			<part name="satellite dish" number="1" />
		</outputs>
	</process>

	<process name="make steel barrel" tech="1" skill="1" work-time="10" process-time="10"
			power-required="0.1">
		<inputs>
			<part name="steel sheet" number="1" />
		</inputs>
		<outputs>
			<equipment name="barrel" number="6" />
		</outputs>
	</process>

	<process name="make polyethylene barrel" tech="1" skill="1" work-time="10" process-time="10"
			power-required="0.1">
		<inputs>
			<resource name="polyethylene" amount="7.8" />
		</inputs>
		<outputs>
			<equipment name="barrel" number="6" />
		</outputs>
	</process>

	<process name="make steel specimen box" tech="1" skill="1" work-time="10" process-time="10"
			power-required=".1">
		<inputs>
			<part name="steel sheet" number="1" />
		</inputs>
		<outputs>
			<equipment name="specimen box" number="12" />
		</outputs>
	</process>

	<process name="make plastic specimen box" tech="1" skill="1" work-time="10" process-time="10"
			power-required=".1">
		<inputs>
			<resource name="polyethylene" amount="7.8" />
		</inputs>
		<outputs>
			<equipment name="specimen box" number="12" />
		</outputs>
	</process>

	<!-- Produces 10kg steel canister. -->
	<process name="make steel canister" tech="1" skill="1" work-time="10" process-time="10"
			 power-required=".1">
		<inputs>
			<!-- one steel sheet weighs 7.8 kg -->
			<part name="steel sheet" number="1" />
		</inputs>
		<outputs>
			<resource name="iron powder" amount="0.4" />
			<!-- one steel canister weighs 3.9 kg -->
			<part name="steel canister" number="2" />
		</outputs>
	</process>

	<process name="make gas canister" tech="1" skill="1" work-time="5" process-time="5"
			power-required="0.1">
		<inputs>
			<part name="steel canister" number="1" />
			<part name="valve" number="2" />
			<part name="gasket" number="1" />
		</inputs>
		<outputs>
			<!-- one gas canister weighs 4 kg -->
			<equipment name="gas canister" number="1" />
		</outputs>
	</process>

	<!-- Using reinforced fiberglass wrapped in aluminum sheeting to make antenna. -->
	<process name="make radio antenna" tech="2" skill="2" work-time="100" process-time="100"
			power-required=".3">
		<inputs>
			<resource name="polyester resin" amount=".5" />
			<resource name="styrene" amount=".5" />
			<part name="fiberglass" number="1" />
			<part name="aluminum sheet" number="1" />
			<part name="electrical wire" number="1" />
			<part name="wire connector" number="3" />
			<part name="optical cable" number="1" />
		</inputs>
		<outputs>
			<part name="radio antenna" number="5" />
		</outputs>
	</process>

	<process name="make suit heating unit" tech="2" skill="2" work-time="100" process-time="100"
			power-required="0.3">
		<inputs>
			<part name="aluminum sheet" number="1" />
			<part name="heating element" number="1" />
			<part name="heat pipe" number="1" />
			<part name="electrical wire" number="1" />
			<part name="wire connector" number="4" />
		</inputs>
		<outputs>
			<part name="suit heating unit" number="5" />
		</outputs>
	</process>

	<!-- Produces 1kg plastic pipe. -->
	<process name="make plastic pipe" tech="1" skill="1" work-time="100" process-time="400"
			power-required=".1">
		<inputs>
			<resource name="polyethylene" amount="10.0" />
		</inputs>
		<outputs>
			<part name="plastic pipe" number="10" />
		</outputs>
	</process>

	<process name="make plastic bottle" tech="1" skill="1" work-time="100" process-time="100"
			power-required=".1">
		<inputs>
			<resource name="polyethylene" amount="1.0" />
		</inputs>
		<outputs>
			<part name="bottle" number="10" />
		</outputs>
	</process>

	<process name="make clear glass bottle" tech="2" skill="1" work-time="200" process-time="200"
			power-required=".1">
		<inputs>
			<resource name="sand" amount="1.0" />
		</inputs>
		<outputs>
			<part name="bottle" number="10" />
		</outputs>
	</process>

	<process name="produce petri dish" tech="2" skill="2" work-time="50" process-time="40"
			power-required=".1">
		<inputs>
			<resource name="polystyrene" amount="1.5" />
		</inputs>
		<outputs>
			<part name="petri dish" number="50" />
		</outputs>
	</process>
	
	<process name="make gasket" tech="4" skill="2" work-time="100" process-time="200"
			power-required=".1">
		<inputs>
			<resource name="styrene" amount="2.0" />
		</inputs>
		<outputs>
			<part name="gasket" number="20" />
		</outputs>
	</process>

	<!-- Use fiberglass & styrene to make belt. -->
	<process name="make timing belt" tech="4" skill="2" work-time="100" process-time="200"
			power-required=".2">
		<inputs>
			<resource name="styrene" amount="1.0" />
			<part name="fiberglass cloth" number="1" />
		</inputs>
		<outputs>
			<part name="timing belt" number="5" />
		</outputs>
	</process>

	<process name="make plastic tubing" tech="4" skill="2" work-time="100" process-time="200"
			power-required=".05">
		<inputs>
			<resource name="styrene" amount="1.0" />
		</inputs>
		<outputs>
			<part name="plastic tubing" number="10" />
		</outputs>
	</process>

	<process name="produce polyester resin" tech="2" skill="1" work-time="10" process-time="40"
			power-required="0.05">
		<description>
			This is to produce unsaturated polyester resin (C&lt;sub&gt;10&lt;/sub&gt;H&lt;sub&gt;8&lt;/sub&gt;O&lt;sub&gt;4&lt;/sub&gt;).
			We don't have a detailed process for producing polyester, so we're just using component elements.
		</description>
		<inputs>
			<resource name="carbon" amount="30.0" />
			<resource name="water" amount="20.0" />
		</inputs>
		<outputs>
			<resource name="polyester resin" amount="50.0" />
		</outputs>
	</process>

	<!-- This is to produce unsaturated polyester resin (C10H8O4). -->
	<!-- We don't have a detailed process for producing polyester, so we're just using component elements. -->
	<process name="produce polyester resin (large batch)" tech="2" skill="1" work-time="50" process-time="200"
			power-required="0.1">
		<inputs>
			<resource name="carbon" amount="300.0" />
			<resource name="water" amount="200.0" />
		</inputs>
		<outputs>
			<resource name="polyester resin" amount="500.0" />
		</outputs>
	</process>

	<process name="roll mylar film" tech="2" skill="2" work-time="10" process-time="40"
			power-required="0.05">
		<description>
		 Mylar coated with evaporated aluminum on one side
		</description>
		<inputs>
			<resource name="polyester resin" amount="1.0" />
			<resource name="polyethylene" amount="1.0" />
		</inputs>
		<outputs>
			<resource name="mylar" amount="2.0" />
		</outputs>
	</process>
	
	<process name="roll aluminized mylar foil" tech="2" skill="2" work-time="10" process-time="40"
			power-required="0.05">
		<description>
		 Biaxially oriented PET film is metallized by vapor deposition of a thin film of 
		 evaporated aluminium, gold, or other metal onto it.
		</description>
		<inputs>
			<resource name="mylar" amount="2.0" />
			<resource name="aluminum" amount="0.5" />
		</inputs>
		<outputs>
			<resource name="aluminized mylar" amount="2.5" />
		</outputs>
	</process>
	
	<!-- Epoxy uses bisphenol-a (C15H16O2) -->
	<process name="make epoxy resin bottle" tech="3" skill="1" work-time="20" process-time="300"
			power-required="0.1">
		<inputs>
			<resource name="bisphenol-a" amount=".5" />
			<part name="bottle" number="5" />
		</inputs>
		<outputs>
			<part name="epoxy resin bottle" number="5" />
		</outputs>
	</process>

	<!-- Using polyester resin as a lubricant. -->
	<process name="make lubricant bottle" tech="3" skill="1" work-time="20" process-time="300"
			power-required="0.1">
		<inputs>
			<resource name="polyester resin" amount=".5" />
			<part name="bottle" number="5" />
		</inputs>
		<outputs>
			<part name="lubricant bottle" number="5" />
		</outputs>
	</process>

	<process name="make coolant bottle" tech="3" skill="1" work-time="20" process-time="300"
			power-required="0.1">
		<description>
			Using ethylene glycol as a coolant.
			C&lt;sub&gt;2&lt;/sub&gt;H&lt;sub&gt;4&lt;/sub&gt;O + H&lt;sub&gt;2&lt;/sub&gt;O -> HOCH&lt;sub&gt;2&lt;/sub&gt;CH&lt;sub&gt;2&lt;/sub&gt;OH
		</description>
		<inputs>
			<resource name="ethylene" amount=".35" />
			<resource name="water" amount=".15" />
			<part name="bottle" number="5" />
		</inputs>
		<outputs>
			<part name="coolant bottle" number="5" />
		</outputs>
	</process>

	<process name="make airleak patch" tech="3" skill="1" work-time="20" process-time="100"
			power-required="0.1">
		<inputs>
			<resource name="polyester resin" amount="7.5" />
			<resource name="styrene" amount="7.5" />
			<part name="epoxy resin bottle" number="5" />
		</inputs>
		<outputs>
			<part name="airleak patch" number="10" />
		</outputs>
	</process>

	<!-- Spark plug insulator uses aluminum oxide ceramic -->
	<process name="make spark plug" tech="2" skill="2" work-time="200" process-time="200"
			power-required=".1">
		<inputs>
			<resource name="aluminum oxide" amount=".5" />
			<resource name="lime" amount="2" />
			<resource name="iron" amount="2" />
			<resource name="copper" amount="2" />
			<part name="steel ingot" number="1" />
		</inputs>
		<outputs>
			<part name="spark plug" number="100" />
		</outputs>
	</process>

	<!-- Produces 1kg spool of fiber glass. -->
	<process name="draw optical fiber glass" tech="3" skill="1" work-time="50" process-time="100"
			power-required=".1">
		<inputs>
			<resource name="sand" amount="2.0" />
		</inputs>
		<outputs>