<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<!DOCTYPE mineral-concentrations [
	<!ELEMENT mineral-concentrations (mineral*)>
	<!ELEMENT mineral (locale-list)>
	<!ATTLIST mineral name CDATA #REQUIRED>
	<!ATTLIST mineral frequency (common|uncommon|rare|very_rare) #REQUIRED>
	<!ELEMENT locale-list (locale+)>
	<!ELEMENT locale EMPTY>
	<!ATTLIST locale name (volcanic|sedimentary|crater) #REQUIRED>
]>

<!-- List of all mineral concentrations that can be mined. -->
<mineral-concentrations>

	<!-- Hematite is an iron ore. -->
	<!-- http://en.wikipedia.org/wiki/Hematite -->
	<!-- frequency - how common are the mineral concentrations? -->
	<!-- Valid values: "common", "uncommon", "rare", "very_rare" -->
	<!-- 
		1. https://science.nasa.gov/science-news/science-at-nasa/2001/ast28mar_1
		
		In 1998, an infrared spectrometer on NASA's Mars Global Surveyor (MGS) spacecraft 
		detected a substantial deposit of gray hematite near the Martian equator, in a 500 
		km-wide region called Sinus Meridiani. 
		
		The discovery raised the tantalizing possibility that hot springs were once active
		on Mars.
		
		Gray hematite has the same chemical formula (Fe2O3) as its rusty-red cousin, but 
		a different crystalline structure. Red rust is fine and powdery; typical grains 
		are hundreds of nanometers to a few microns across. Gray hematite crystals are 
		larger, like grains of sand.

		Red and gray iron oxides on Mars are different forms of the same 
		mineral. 
		
		Ground up the gray hematite into a fine powder it would turn red because the 
		smaller grains scatter red light.

		The coarse-grained structure of gray hematite is important because "to get that 
		kind of coarsening of the crystallinity, you would need to have a reasonable 
		amount of water available" where the hematite formed.
		
		Some of them, like carbonates, would also indicate that standing bodies of 
		water were present on the surface.
		
		Hematite minerals, on the other hand, might have been formed by hydrothermal
		water deep underground.
	-->
	<mineral name="Hematite" frequency="common">
		<locale-list>
			<!-- locale topographical regions the mineral is located. -->
			<!-- Valid values: "volcanic", "sedimentary", "crater" -->
			<locale name="volcanic" />
			<locale name="sedimentary" />
		</locale-list>
	</mineral>
	
	<!-- Magnetite is an iron ore with volcanic and metamorphic origins. -->
	<!-- http://en.wikipedia.org/wiki/Magnetite -->
	<mineral name="Magnetite" frequency="rare">
		<locale-list>
			<locale name="volcanic" />
			<locale name="sedimentary" />
		</locale-list>
	</mineral>
	
	<!-- Magnesite is a magnesium carbonate with metamorphic origins. -->
	<!-- http://en.wikipedia.org/wiki/Magnesite -->
	<mineral name="Magnesite" frequency="rare">
		<locale-list>
			<locale name="sedimentary" />
		</locale-list>
	</mineral>
	
	<!-- Olivine is a magnesium iron silicate found in meteorites. -->
 	<!-- 
 		1. https://zenodo.org/record/1230836
 		
 		30,000-square-kilometer area rich in olivine in the Nili Fossae region of Mars. 
 		Nili Fossae has been interpreted as a complex of grabens and fractures related to 
 		the formation of the Isidis impact basin.
 	
 		2. http://en.wikipedia.org/wiki/Olivine 
 	
 		Mg-rich olivine has also been discovered in meteorites, on the Moon and Mars, falling 
 		into infant stars, as well as on asteroid 25143 Itokawa.
 		
 		3. https://en.wikipedia.org/wiki/Composition_of_Mars
 		
     	The mineral olivine occurs all over the planet, but some of the largest concentrations 
     	are in Nili Fossae, an area containing Noachian-aged rocks. Another large olivine-rich
     	outcrop is in Ganges Chasma, an eastern side chasm of Valles Marineris. 
     	
     	Olivine weathers rapidly into clay minerals in the presence of liquid water. 
     	Therefore, areas with large outcroppings of olivine-bearing rock indicate that liquid 
     	water has not been abundant since the rocks formed.
 	-->
	<mineral name="Olivine" frequency="uncommon">
		<locale-list>
			<locale name="crater" />
		</locale-list>
	</mineral>
	
	<!-- Goethite is an iron ore that has metamorphic origins. -->
	<!-- http://en.wikipedia.org/wiki/Goethite -->
	<mineral name="Goethite" frequency="common">
		<locale-list>
			<locale name="sedimentary" />
		</locale-list>
	</mineral>
	
	<!-- Kamacite is an iron-nickel mineral found in meteorites. -->
	<!-- http://en.wikipedia.org/wiki/Kamacite -->
	<mineral name="Kamacite" frequency="common">
		<locale-list>
			<locale name="crater" />
		</locale-list>
	</mineral>
	
	<!-- Taenite is an iron-nickel mineral found in meteorites. -->
	<!-- http://en.wikipedia.org/wiki/Taenite -->
	<mineral name="Taenite" frequency="common">
		<locale-list>
			<locale name="crater" />
		</locale-list>
	</mineral>
	
	<!-- Chalcopyrite is a copper sulfide mineral. -->
	<!-- http://en.wikipedia.org/wiki/Chalcopyrite -->
	<mineral name="Chalcopyrite" frequency="uncommon">
		<locale-list>
			<locale name="sedimentary" />
			<locale name="volcanic" />
		</locale-list>
	</mineral>
	
	<!-- Malachite is a copper carbonate mineral. -->
	<!-- http://en.wikipedia.org/wiki/Malachite -->
	<mineral name="Malachite" frequency="uncommon">
		<locale-list>
			<locale name="sedimentary" />
			<locale name="volcanic" />
		</locale-list>
	</mineral>
	
	<!-- Sylvite is a salt concentration of potasium chloride. -->
	<!-- http://en.wikipedia.org/wiki/Sylvite -->
	<mineral name="Sylvite" frequency="common">
		<locale-list>
			<locale name="sedimentary" />
		</locale-list>
	</mineral>
	
	<!-- jarosite, Plagioclase, Feldspar, High-Ca Pyroxene, Low-Ca Pyroxene, Quartz,
    Amphibole, Silicates -->
	
	
</mineral-concentrations>