<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<!DOCTYPE part-list [
	<!ELEMENT part-list (part*)>
	<!ELEMENT part (description?,maintenance-entity-list?)>
	<!ATTLIST part name CDATA #REQUIRED>
	<!ATTLIST part type CDATA #REQUIRED>
	<!ATTLIST part mass CDATA #REQUIRED>
	<!ATTLIST part storable (true|false) "false">
	<!ELEMENT description (#PCDATA)>
	<!ELEMENT maintenance-entity-list (entity*)>
	<!ELEMENT entity EMPTY>
	<!ATTLIST entity name CDATA #REQUIRED>
	<!ATTLIST entity probability CDATA #REQUIRED>
	<!ATTLIST entity max-number CDATA #REQUIRED>
]>

<part-list>
		<!--  Note: mass in kg can be a decimal number. -->
		<!--  Note: both probability and max-number must be a whole integer and without decimal places. -->
	<part name="Airleak Patch" type="utility" mass=".2">
		<description>Plastic and adhesive patch for airleak.</description>

<!-- 		<maintenance-entity-list>
			<entity name="life support" probability="5" max-number="4" />
			<entity name="rover" probability="5" max-number="2" />
			<entity name="eva suit" probability="5" max-number="1" />
			<entity name="farming" probability="5" max-number="4" />
		</maintenance-entity-list>
-->
	</part>
	<part name="Fire Extinguisher" type="utility" mass="3" />

	<part name="Gasket" type="utility" mass=".1">
		<maintenance-entity-list>
			<entity name="rover" probability="5" max-number="4" />
			<entity name="farming" probability="5" max-number="6" />
			<entity name="living accommodations" probability="5" max-number="4" />
			<entity name="manufacture" probability="5" max-number="6" />
			<entity name="eva suit" probability="5" max-number="1" />
			<entity name="settlement" probability="5" max-number="2" />
			<entity name="areothermal power source" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="Valve" type="utility" mass=".2">
		<maintenance-entity-list>
			<entity name="rover" probability="5" max-number="2" />
			<entity name="farming" probability="5" max-number="3" />
			<entity name="living accommodations" probability="5" max-number="2" />
			<entity name="manufacture" probability="5" max-number="3" />
			<entity name="eva suit" probability="5" max-number="1" />
			<entity name="settlement" probability="5" max-number="1" />
			<entity name="areothermal power source" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="Plastic Bottle" type="utility" mass=".2">
		<maintenance-entity-list>
			<entity name="vehicle" probability="5" max-number="6" />
			<entity name="farming" probability="5" max-number="12" />
			<entity name="living accommodations" probability="5" max-number="4" />
			<entity name="manufacture" probability="5" max-number="6" />
			<entity name="eva suit" probability="5" max-number="1" />
			<entity name="settlement" probability="5" max-number="4" />
		</maintenance-entity-list>
	</part>

	<part name="Spark Plug" type="electrical" mass=".1">
		<maintenance-entity-list>
			<entity name="rover" probability="5" max-number="2" />
		</maintenance-entity-list>
	</part>

	<part name="Coolant Bottle" type="utility" mass=".2">
		<maintenance-entity-list>
			<entity name="rover" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="Plastic Tubing" type="utility" mass=".1">
		<maintenance-entity-list>
			<entity name="rover" probability="5" max-number="4" />
			<entity name="farming" probability="5" max-number="10" />
			<entity name="manufacture" probability="5" max-number="10" />
		</maintenance-entity-list>
	</part>

	<part name="Lubricant Bottle" type="utility" mass=".2">
		<maintenance-entity-list>
			<entity name="vehicle" probability="5" max-number="4" />
			<entity name="manufacture" probability="5" max-number="2" />
		</maintenance-entity-list>
	</part>

	<part name="Radio Antenna" type="electronic" mass="2.0">
		<maintenance-entity-list>
			<entity name="vehicle" probability="5" max-number="1" />
			<entity name="communication" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="Satellite Dish" type="electronic" mass="4.0">
		<maintenance-entity-list>
			<entity name="vehicle" probability="5" max-number="1" />
			<entity name="communication" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="Timing Belt" type="vehicle" mass=".2">
		<maintenance-entity-list>
			<entity name="rover" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="Communications Circuit Board" type="electronic" mass=".5">
		<maintenance-entity-list>
			<entity name="rover" probability="5" max-number="1" />
			<entity name="communication" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="Navigation Circuit Board" type="electronic" mass=".5">
		<maintenance-entity-list>
			<entity name="rover" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>

	<!-- one steel sheet can make two steel canisters -->
	<part name="Steel Canister" type="utility" mass="3.9" />
	
	<part name="Glass Bottle" type="utility" mass="2.5" />
	
	<part name="Rope" type="utility" mass="2" />

	<part name="Iron Ingot" type="metallic" mass="7.0" />

	<part name="Steel Ingot" type="metallic" mass="5.0" />

	<part name="Aluminum Ingot" type="metallic" mass="5.0" />

	<part name="Steel Sheet" type="metallic" mass="7.8" >
		<description>A density of 7.8 g/cm3. 1m x 1m x 1mm sheet of steel</description>
	</part>

	<part name="Iron Sheet" type="metallic" mass="7.85" >
		<description>A density of 7.85 g/cm3. 1m x 1m x 1mm sheet of iron</description>
	</part>

	<!-- based on https://www.gigacalculator.com/calculators/metal-weight-calculator.php  -->
	<part name="Aluminum Sheet" type="metallic" mass="2.72" >
		<description>A density of 2.72 g/cm3. 1m x 1m x 1mm sheet of aluminum</description>
	</part>

	<part name="Copper Sheet" type="metallic" mass="8.94">
		<description>A density of 8.94 g/cm3. 1m x 1m x 1mm sheet of copper</description>
	</part>

	<!-- a small spool of thin copper wire -->
	<part name="Copper Wire" type="electrical" mass="0.526" />

	<!-- a small spool of thick steel wire -->
	<part name="Steel Wire" type="electrical" mass="0.52" />

	<!-- a small spool of thin aluminum wire -->
	<part name="Aluminum Wire" type="electrical" mass="0.544" />

	<!-- a small spool of thin electrical wire -->
	<part name="Electrical Wire" type="electrical" mass="0.05">
		<maintenance-entity-list>
			<entity name="building" probability="5" max-number="6" />
			<entity name="vehicle" probability="5" max-number="6" />
			<entity name="power generation" probability="5" max-number="4" />
			<entity name="manufacture" probability="5" max-number="4" />
			<entity name="settlement" probability="5" max-number="8" />
		</maintenance-entity-list>
	</part>

	<!-- Composed of 20 electrical wires braided together -->
	<part name="Steel Cable" type="electrical" mass="1" />

	<!-- Composed of 20 electrical wires braided together -->
	<part name="Power Cable" type="electrical" mass="1">
		<maintenance-entity-list>
			<entity name="power generation" probability="1" max-number="2" />
		</maintenance-entity-list>
	</part>

	<part name="Wire Connector" type="electrical" mass=".005">
		<maintenance-entity-list>
			<entity name="vehicle" probability="5" max-number="6" />
			<entity name="power generation" probability="5" max-number="4" />
			<entity name="manufacture" probability="5" max-number="4" />
		</maintenance-entity-list>
	</part>

	<part name="Steel Pipe" type="metallic" mass="0.882">
	<description>A density of 7.8 g/cm3. length of 1m. Thickness of 2mm. Diameter of 20mm</description>
		<maintenance-entity-list>
			<entity name="farming" probability="1" max-number="2" />
			<entity name="manufacture" probability="1" max-number="2" />
			<entity name="rover" probability="1" max-number="1" />
			<entity name="settlement" probability="1" max-number="2" />
		</maintenance-entity-list>
	</part>

	<part name="Iron Pipe" type="metallic" mass="0.888">
		<description>A density of 7.85 g/cm3. length of 1m. Thickness of 2mm. Diameter of 20mm</description>
		<maintenance-entity-list>
			<entity name="farming" probability="1" max-number="2" />
			<entity name="manufacture" probability="1" max-number="2" />
			<entity name="rover" probability="1" max-number="1" />
			<entity name="settlement" probability="1" max-number="2" />
		</maintenance-entity-list>
	</part>

	<part name="Copper Pipe" type="metallic" mass="	1.011">
		<description>A density of 8.94 g/cm3. length of 1m. Thickness of 2mm. Diameter of 20mm</description>
		<maintenance-entity-list>
			<entity name="living accommodations" probability="2" max-number="1" />
			<entity name="farming" probability="2" max-number="2" />
			<entity name="manufacture" probability="2" max-number="2" />
			<entity name="settlement" probability="2" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="Plastic Pipe" type="utility" mass="1.0">
		<maintenance-entity-list>
			<entity name="living accommodations" probability="5" max-number="2" />
			<entity name="farming" probability="5" max-number="4" />
			<entity name="manufacture" probability="5" max-number="2" />
			<entity name="rover" probability="5" max-number="1" />
			<entity name="settlement" probability="5" max-number="4" />
		</maintenance-entity-list>
	</part>

	<!-- 1kg spool of thin fiberglass -->
	<part name="Fiberglass" type="utility" mass="1.0" />

	<!-- 1m x 1m square of woven fiberglass cloth -->
	<part name="Fiberglass Cloth" type="utility" mass=".1" />

	<!-- 1m x 1m square of thin plastic sheet -->
	<part name="Plastic Sheet" type="utility" mass=".1" />

	<!-- 1m x 1m x 1cm square of glass  -->
	<part name="Glass Sheet" type="utility" mass="26.0" />

	<part name="Garment" type="utility" mass="0.5" >
		<description>a standard set of clothing for indoor use.</description>
	</part>

	<part name="EVA Helmet" type="EVA" mass="1.0" >
		<maintenance-entity-list>
			<entity name="eva suit" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="Helmet Visor" type="EVA" mass="0.5" >
		<maintenance-entity-list>
			<entity name="eva suit" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="Pressure Suit" type="EVA" mass="1.0" >
		<description>Spandex inner EVA suit for counter pressure.</description>
		<maintenance-entity-list>
			<entity name="eva suit" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="Coveralls" type="EVA" mass="1.0" >
		<description>Outer EVA suit with insulative liner.</description>
		<maintenance-entity-list>
			<entity name="eva suit" probability="1" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="Suit Heating Unit" type="EVA" mass="0.25">
		<maintenance-entity-list>
			<entity name="eva suit" probability="1" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="EVA Gloves" type="EVA" mass="0.1" >
		<maintenance-entity-list>
			<entity name="eva suit" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="EVA Boots" type="EVA" mass="2.0" >
		<description>steel soled and tipped.  Fiberglass insulated.</description>
		<maintenance-entity-list>
			<entity name="eva suit" probability="2" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="EVA Pads" type="EVA" mass="0.5" >
		<description>steel plate with fiberglass insulation.</description>
		<maintenance-entity-list>
			<entity name="eva suit" probability="2" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="EVA backpack" type="EVA" mass="5.0" >
		<description>The backpack is the most crucial part of the Portable Life-Support System (PLSS).
		It is made with polyethylene and a steel frame.</description>
		<maintenance-entity-list>
			<entity name="eva suit" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="EVA Antenna" type="EVA" mass=".05" >
		<maintenance-entity-list>
			<entity name="eva suit" probability="2" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="EVA Battery" type="EVA" mass="1.2" >
		<description>Assuming the future achievement of 1 kg/kWh or 1 kWh/kg, this 
		rechargeable battery module is rated for 150 W at 18V 
		for providing 8 hrs of electrical power to the EVA suit. 
		Total energy capacity is 150 * 8 = 1.2 kWh. Weight: 1.2/1 = 1.2 kg
		</description>
		<maintenance-entity-list>
			<entity name="eva suit" probability="2" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="EVA Radio" type="EVA" mass="0.25" >
		<maintenance-entity-list>
			<entity name="eva suit" probability="2" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="Vehicle Frame - large" type="vehicle" mass="250.0">
		<description>Heavy steel frame</description>
	</part>

	<part name="Rover Chassis Panel" type="vehicle" mass="100.0" >
		<description>Reinforced fiberglass panels.</description>
		<maintenance-entity-list>
			<entity name="rover" probability="5" max-number="10" />
		</maintenance-entity-list>
	</part>

	<part name="Battery Module" type="vehicle" mass="15.0">
		<description>Assuming the future achievement of 1 kg/kWh or 1 kWh/kg, 
		this 15kWh rechargeable battery provides 'auxiliary' 
		electrical power to the vehicle, on top of the primary
		fuel cell stack. It operates at 400V. With 15 kWh capacity,
		or 37.5 Ah (= 15/.4). Assume 6.43 km/kWh (based on a Tesla Model S
		battery pack weighing 2240 kg with 100 kWh capacity that can travel 
		643 km), this battery allows traveling a distance of 96.5 km on a single charge.
		</description>
		<maintenance-entity-list>
			<entity name="rover" probability="2" max-number="4" />
			<entity name="luv" probability="2" max-number="1" />
			<entity name="delivery drone" probability="2" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="Rover Wheel" type="vehicle" mass="8.9">
		<description>Rover wheels are made of steel and steel wire.</description>
		<maintenance-entity-list>
			<entity name="rover" probability="5" max-number="4" />
		</maintenance-entity-list>
	</part>

	<part name="Rover Windshield" type="vehicle" mass="100.0" >
		<maintenance-entity-list>
			<entity name="rover" probability=".5" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="Rover Window" type="vehicle" mass="50.0" >
		<maintenance-entity-list>
			<entity name="rover" probability=".5" max-number="5" />
		</maintenance-entity-list>
	</part>

	<part name="Rover Generator" type="vehicle" mass="500.0" >
		<maintenance-entity-list>
			<entity name="rover" probability="5" max-number="1" />
			<entity name="fuel power source" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="Motor - Large" type="vehicle" mass="100.0" >
		<maintenance-entity-list>
			<entity name="rover" probability="5" max-number="4" />
			<entity name="wind power source" probability="1" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="Rover Control Panel" type="vehicle" mass="100.0" >
		<description>Made from polyethylene and reinforced fiberglass.</description>
		<maintenance-entity-list>
			<entity name="rover" probability=".5" max-number="1" />
		</maintenance-entity-list>
	</part>


	<part name="Gas Tank" type="utility" mass="20.0" >
	 	<maintenance-entity-list>
			<entity name="rover" probability="5" max-number="1" />
			<entity name="life support" probability="1" max-number="1" />
			<entity name="fuel heating source" probability="3" max-number="1" />
			<entity name="cooking" probability="3" max-number="1" />
			<entity name="farming" probability="3" max-number="5" />
		</maintenance-entity-list>
	</part>

	<part name="Water Tank" type="utility" mass="20.0" >
	 	<maintenance-entity-list>
			<entity name="rover" probability="5" max-number="1" />
			<entity name="life support" probability="1" max-number="1" />
			<entity name="fuel heating source" probability="5" max-number="1" />
			<entity name="cooking" probability="5" max-number="1" />
			<entity name="farming" probability="5" max-number="5" />
		</maintenance-entity-list>
	</part>

	<part name="Fuel Tank" type="utility" mass="50.0" >
	<description>for storing methane</description>
		<maintenance-entity-list>
			<entity name="rover" probability="5" max-number="1" />
			<entity name="life support" probability="1" max-number="1" />
			<entity name="fuel heating source" probability="5" max-number="1" />
			<entity name="cooking" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="Heating Element" type="electrical" mass="1.0" >
		<description>The heating element is a thermofoil conductive
		electrical element embedded in a thin Kapton substrate.</description>
		<maintenance-entity-list>
			<entity name="life support" probability="1" max-number="1" />
			<entity name="rover" probability="2" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="Pneumatic Drill" type="attachment" mass="25.0">
		<description>Attachment part for LUV. A pneumatic hand for lifting.</description>
	</part>

	<part name="Backhoe" type="attachment" mass="35.0" >
		<description>Attachment part for LUV. An excavating equipment with a digging bucket on the end of a two-part articulated arm</description>
	</part>

	<part name="Bulldozer Blade" type="attachment" mass="40.0">
		<description>Attachment part for LUV. A bulldozer blade (possible use for new structures).</description>
	</part>

	<part name="Soil Compactor" type="attachment" mass="100.0">
		<description>Attachment part for LUV. A drum roller that applied stress to a soil</description>
	</part>

	<part name="Crane Boom" type="attachment" mass="75.0">
		<description>Attachment part for LUV. A long, telescopic or fixed arm for moving objects</description>
	</part>

	<part name="Motor - small" type="electrical" mass="10.0" >
		<maintenance-entity-list>
			<entity name="robot" probability="1" max-number="1" />
			<entity name="luv" probability="1" max-number="4" />
			<entity name="delivery drone" probability="1" max-number="4" />
		</maintenance-entity-list>
	</part>

	<part name="Vehicle Frame - small" type="vehicle" mass="75.0" />

	<part name="Wheel - small" type="vehicle"  mass="4.45" >
		<maintenance-entity-list>
			<entity name="luv" probability="5" max-number="2" />
		</maintenance-entity-list>
	</part>

	<part name="Utility Vehicle Control Panel" type="vehicle" mass="10" >
		<maintenance-entity-list>
			<entity name="luv" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="Steel Truss" type="construction" mass="50.0">
		<description>Large steel bar used for construction.</description>
	</part>

	<part name="Steel Post" type="construction" mass="5.0">
		<description>A small, light steel bar used for construction.</description>
	</part>

	<part name="Wind Turbine Blade" type="electrical" mass="2.0" >
		<description>Blade for a wind turbine.</description>
		<maintenance-entity-list>
			<entity name="wind power source" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="Turbine Generator" type="electrical" mass="50.0" >
		<description>Turbine power generator.</description>
		<maintenance-entity-list>
			<entity name="wind power source" probability="5" max-number="1" />
			<entity name="areothermal power source" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="Solar Panel" type="electrical" mass="10.0" >
		<description>Solar photovoltaic panel.</description>
		<maintenance-entity-list>
			<entity name="solar power source" probability="3" max-number="1" />
			<entity name="electric heat source" probability="3" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="Solar Parabolic Mirror" type="electrical" mass="50.0" >
		<description>Mirror for solar thermal power source.</description>
		<maintenance-entity-list>
			<entity name="solar thermal power source" probability="3" max-number="1" />
			<entity name="solar heat source" probability="3" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="Glass Tube" type="electrical" mass="5.0" >
		<description>Long transparent glass tube.</description>
		<maintenance-entity-list>
			<entity name="solar thermal power source" probability="2" max-number="1" />
<!--
			<entity name="large algae greenhouse" probability="5" max-number="1" />
-->
		</maintenance-entity-list>
	</part>
<!--
	<part name="algae tank" mass="200.0">
		<description>An array of glass tubes connected with pipes and held together by a metal frame.</description>
	</part>
-->
	<part name="Brick" type="construction" mass="2.86">
		<!-- (UK Standard according to Wikipedia) -->
		<description>Construction brick (215mm x 102.5mm x 65mm) 2.86kg</description>
	</part>

	<part name="Steel Scrap" type="metallic" mass="25.0">
		<description>A 25 kg piece of salvaged steel scrap.</description>
	</part>

	<part name="Aluminum Scrap" type="metallic" mass="5.0">
		<description>A 5 kg piece of salvaged aluminum scrap.</description>
	</part>

	<part name="Bore Drill Bit" type="tool" mass="25.0">
		<description>A steel drill bit for drilling bore holes.</description>
	</part>

	<part name="Bore Drill Pipe" type="tool" mass="50.0">
		<description>A steel pipe for drilling and lining bore holes.</description>
	</part>

	<part name="Drilling Rig" type="tool" mass="135.0">
		<description>
			An attachment for luv. A motor platform for supporting drilling (used in conjunction with the crane boom)
		</description>
	</part>

	<part name="Condenser Coil" type="electrical" mass="10.0" >
		<description>Copper tube coil used to condense steam into liquid water.</description>
		<maintenance-entity-list>
			<entity name="areothermal power source" probability="2" max-number="1" />
		</maintenance-entity-list>
	</part>

	<!-- 2014-11-19 Added an air compressor. -->
	<part name="Air Compressor" type="electrical" mass="2.0" >
	 	<maintenance-entity-list>
			<entity name="farming" probability="5" max-number="3" />
			<entity name="cooking" probability="5" max-number="3" />
		</maintenance-entity-list>
	</part>

	<!-- 2014-11-19 Added a magnetron tube.
	<part name="magnetron tube" mass="0.5" >
	</part>
	-->

	<!-- Add power transistor, replacaing the use of heavy, bulky magnetron tube used in microwave oven.
	see http://www.nxp.com/products/rf/rf-power-transistors/rf-cooking:RF-COOKING?cof=0&am=0   -->
	<part name="Power Transistor" type="electronic" mass="0.01" >
		<maintenance-entity-list>
		<entity name="farming" probability="1" max-number="2" />
		<entity name="vehicle" probability="1" max-number="2" />
		<entity name="manufacture" probability="1" max-number="2" />
		<entity name="living accommodations" probability="1" max-number="1" />
		</maintenance-entity-list>
	</part>


	<!-- 2014-11-19 Added a microcontroller. -->
	<part name="Microcontroller" type="electronic" mass="0.1" >
		<maintenance-entity-list>
		<entity name="farming" probability="1" max-number="1" />
		<entity name="vehicle" probability="1" max-number="1" />
		<entity name="manufacture" probability="1" max-number="1" />
		<entity name="living accommodations" probability="1" max-number="1" />
		</maintenance-entity-list>
	</part>

	<!-- 2014-11-19 Added transformer. -->
	<part name="Transformer" type="electrical" mass="5.0" >
		<maintenance-entity-list>
		<entity name="farming" probability="3" max-number="1" />
		<entity name="vehicle" probability="3" max-number="1" />
		<entity name="manufacture" probability="3" max-number="2" />
		<entity name="living accommodations" probability="3" max-number="1" />
		</maintenance-entity-list>
	</part>

	<!-- 2014-11-19 Added 7 kitchen equipment below -->
	<part name="Blender" type="kitchen" mass="2.0">
		<maintenance-entity-list>
			<entity name="cooking" probability="3" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="Oven" type="kitchen" mass="10.0">
		<maintenance-entity-list>
			<entity name="cooking" probability="3" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="Microwave" type="kitchen" mass="3.0">
		<maintenance-entity-list>
			<entity name="cooking" probability="3" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="Ventilation fan" type="electrical" mass="0.2">
		<maintenance-entity-list>
			<entity name="cooking" probability="3" max-number="1" />
			<entity name="farming" probability="3" max-number="3" />
			<entity name="vehicle" probability="3" max-number="1" />
			<entity name="manufacture" probability="3" max-number="3" />
			<entity name="living accommodations" probability="3" max-number="2" />
		</maintenance-entity-list>
	</part>

	<part name="Stove" type="kitchen" mass="20.0">
		<maintenance-entity-list>
			<entity name="cooking" probability="3" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="Refrigerator" type="kitchen" mass="70.0">
		<maintenance-entity-list>
			<entity name="cooking" probability="3" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="Autoclave" type="kitchen" mass="20.0">
		<maintenance-entity-list>
			<entity name="cooking" probability="3" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="Light Emitting Diode kit" type="electronic" mass="1.0">
		<maintenance-entity-list>
			<entity name="cooking" probability="3" max-number="5" />
			<entity name="farming" probability="3" max-number="15" />
			<entity name="vehicle" probability="3" max-number="3" />
			<entity name="manufacture" probability="3" max-number="10" />
			<entity name="living accommodations" probability="3" max-number="10" />
			<entity name="life support" probability="5" max-number="4" />
		</maintenance-entity-list>
	</part>

	<part name="Light Emitting Diode bulb" type="electronic" mass="0.1">
		<description>Solid State Light bulb</description>
	</part>

	<part name="High Pressure Sodium lamp" type="electrical" mass="0.3">
		<description>High Intensity Discharge (HID), and more specifically, High Pressure Sodium (HPS)
			lights have long been used as indoor grow lights, particularly for the late vegetative
			and flowering/fruiting stages of growth.</description>
		<maintenance-entity-list>
			<entity name="farming" probability="3" max-number="2" />
		</maintenance-entity-list>
	</part>

	<part name="Mushroom Containment kit" type="tool" mass="1.0">
		<maintenance-entity-list>
			<entity name="farming" probability="1" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="Semiconductor Wafer" type="electronic" mass="1"/>

	<part name="Laser Sintering 3D printer" type="electronic" mass="50.0">
		<maintenance-entity-list>
			<entity name="manufacture" probability="3" max-number="2" />
		</maintenance-entity-list>
	</part>

	<part name="Carbon Dioxide laser" type="electronic" mass="5.0"/>

	<part name="Helium Neon laser" type="electronic" mass="1.0"/>

	<part name="Optical Lens" type="electronic" mass=".1" >
			<maintenance-entity-list>
			<entity name="communication" probability="2" max-number="2" />
		</maintenance-entity-list>
	</part>

	<part name="Optical Prism" type="electronic" mass=".1"/>

	<part name="Pathogen filter" type="utility" mass="3.0">
		<maintenance-entity-list>
			<entity name="farming" probability="1" max-number="2" />
			<entity name="dining" probability="2" max-number="2" />
			<entity name="living accommodation" probability="2" max-number="2" />
			<entity name="eva" probability="3" max-number="3" />
			<entity name="exercise" probability="1" max-number="1" />
			<entity name="waste disposal" probability="3" max-number="2" />
			<entity name="vehicle" probability="1" max-number="1" />
			<entity name="medical care" probability="1" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="Charcoal filter" type="utility" mass="1"/>

	<part name="Electrostatic Precipitator" type="utility" mass=".7">
		<description>A filterless device that removes fine particles,
			like dust and smoke, from a flowing gas using the force of
			an induced electrostatic charge minimally impeding the
			flow of gases through the unit</description>
		<maintenance-entity-list>
			<entity name="farming" probability="1" max-number="1" />
			<entity name="dining" probability="2" max-number="1" />
			<entity name="living accommodation" probability="2" max-number="1" />
			<entity name="eva" probability="3" max-number="1" />
			<entity name="waste disposal" probability="3" max-number="1" />
			<entity name="vehicle" probability="1" max-number="1" />
			<entity name="medical care" probability="1" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="Air Duct" type="utility" mass=".3">
		<maintenance-entity-list>
			<entity name="cooking" probability="2" max-number="2" />
			<entity name="farming" probability="2" max-number="2" />
			<entity name="manufacture" probability="2" max-number="2" />
			<entity name="living accommodations" probability="2" max-number="2" />
			<entity name="life support" probability="2" max-number="2" />
		</maintenance-entity-list>
	</part>

	<part name="Flexible hose" type="utility" mass=".1"/>

	<part name="Polycarbonate roofing" type="utility" mass="1">
		<description>highly transparent, "bullet-resistant" plastic cladding
			roofing for greenhouses</description>
	</part>

	<part name="Stepper Motor - small" type="electrical" mass="2">
		<description>precision motor for use in 3D printing</description>
		<maintenance-entity-list>
			<entity name="manufacture" probability="1" max-number="2" />
		</maintenance-entity-list>
	</part>

	<part name="Methane Fuel cell" type="electronic" mass=".2">
		<description>Assume each solid oxide fuel cell (SOFC) can generate 200W
		with the achievement of 1kWh/kg. Weight: 200W * 1kWh/kg = 0.2 kg
		</description>
	</part>

	<part name="Methane Fuel cell stack" type="electronic" mass="60">