<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<!DOCTYPE robot-configuration [
	<!ELEMENT robot-configuration (min-air-pressure, 
	min-temperature, max-temperature, freezing-time, robot-list)>
	<!ELEMENT min-air-pressure EMPTY>
	<!ATTLIST min-air-pressure value CDATA #REQUIRED>
	<!ELEMENT min-temperature EMPTY>
	<!ATTLIST min-temperature value CDATA #REQUIRED>
	<!ELEMENT max-temperature EMPTY>
	<!ATTLIST max-temperature value CDATA #REQUIRED>
	<!ELEMENT freezing-time EMPTY>
	<!ATTLIST freezing-time value CDATA #REQUIRED>
	<!ELEMENT robot-list (robot*)>
	<!ELEMENT robot (robotic-attribute-list?, skill-list?)>
	<!ATTLIST robot type CDATA #REQUIRED>
	<!ATTLIST robot make CDATA #REQUIRED>
	<!ATTLIST robot standby-power-consumption  CDATA #IMPLIED>
	<!ATTLIST robot fuel-consumption-rate CDATA #IMPLIED>
	<!ATTLIST robot low-power-mode CDATA #IMPLIED>
	<!ELEMENT robotic-attribute-list (robotic-attribute*)>
	<!ELEMENT robotic-attribute EMPTY>
	<!ATTLIST robotic-attribute name CDATA #REQUIRED>
	<!ATTLIST robotic-attribute value CDATA #REQUIRED>
	<!ELEMENT skill-list (skill*)>
	<!ELEMENT skill EMPTY>
	<!ATTLIST skill name CDATA #REQUIRED>
	<!ATTLIST skill level CDATA #REQUIRED>
]>

<robot-configuration>
	
	<!-- Minimum air pressure (Pa) a robt can withstand without harm -->
	<min-air-pressure value="500" />

	<!-- Minimum temperature (degrees celsius) a robot can withstand without harm -->
	<min-temperature value="-30.0" />

	<!-- Maximum temperature (degrees celsius) a robot can withstand without harm -->
	<max-temperature value="78.0" />

	<!-- Number of millisols a robot can survive below minimum temperature -->
	<!-- Note: 1 millisol = 88.77 seconds -->
	<freezing-time value="500.0" />

	<!-- List of robot type -->
	<robot-list>

		<robot type="GardenBot" make="standard"
				standby-power-consumption="0.05" fuel-consumption-rate="1" low-power-mode="20">
			<robotic-attribute-list>
				<robotic-attribute name="Strength" value="35"/>
				<robotic-attribute name="Endurance" value="95"/>
				<robotic-attribute name="Agility" value="40"/>
				<robotic-attribute name="Teaching" value="10"/>
				<robotic-attribute name="Experience Aptitude" value="95"/>
				<robotic-attribute name="Conversation" value="10"/>
			</robotic-attribute-list>
			<skill-list>
				<skill name="Botany" level="1"/>
				<skill name="Biology" level="1"/>
			</skill-list>
		</robot>

		<robot type="GardenBot" make="advanced"
				standby-power-consumption="0.05" fuel-consumption-rate="1" low-power-mode="15">
			<robotic-attribute-list>
				<robotic-attribute name="Strength" value="55"/>
				<robotic-attribute name="Endurance" value="95"/>
				<robotic-attribute name="Agility" value="40"/>
				<robotic-attribute name="Teaching" value="40"/>
				<robotic-attribute name="Experience Aptitude" value="95"/>
				<robotic-attribute name="Conversation" value="80"/>
			</robotic-attribute-list>
			<skill-list>
				<skill name="Botany" level="2"/>
				<skill name="Biology" level="2"/>
			</skill-list>
		</robot>
		
		<robot type="MakerBot" make="standard"
					standby-power-consumption="0.05" fuel-consumption-rate="1" low-power-mode="20">
			<robotic-attribute-list>
				<robotic-attribute name="Strength" value="95"/>
				<robotic-attribute name="Endurance" value="95"/>
				<robotic-attribute name="Agility" value="40"/>
				<robotic-attribute name="Teaching" value="50"/>
				<robotic-attribute name="Experience Aptitude" value="95"/>
				<robotic-attribute name="Conversation" value="10"/>
			</robotic-attribute-list>
			<skill-list>
				<skill name="Materials Science" level="1"/>
				<skill name="Physics" level="1"/>				
			</skill-list>
		</robot>				
		
		<robot type="RepairBot" make="standard"
					standby-power-consumption="0.05" fuel-consumption-rate="1" low-power-mode="20">
			<robotic-attribute-list>
				<robotic-attribute name="Strength" value="95"/>
				<robotic-attribute name="Endurance" value="95"/>
				<robotic-attribute name="Agility" value="40"/>
				<robotic-attribute name="Teaching" value="50"/>
				<robotic-attribute name="Experience Aptitude" value="95"/>
				<robotic-attribute name="Conversation" value="10"/>
			</robotic-attribute-list>
			<skill-list>
				<skill name="Mechanics" level="1"/>
				<skill name="Materials Science" level="1"/>
			</skill-list>
		</robot>			
		
		<robot type="ChefBot" make="standard"
					standby-power-consumption="0.05" fuel-consumption-rate="1" low-power-mode="20">
			<robotic-attribute-list>
				<robotic-attribute name="Strength" value="95"/>
				<robotic-attribute name="Endurance" value="95"/>
				<robotic-attribute name="Agility" value="40"/>
				<robotic-attribute name="Teaching" value="10"/>
				<robotic-attribute name="Experience Aptitude" value="95"/>
				<robotic-attribute name="Conversation" value="10"/>
			</robotic-attribute-list>
			<skill-list>
				<skill name="CHEMISTRY" level="1"/>
				<skill name="Cooking" level="1"/>
			</skill-list>
		</robot>
	
		<robot type="MedicBot" make="standard"
					standby-power-consumption="0.05" fuel-consumption-rate="1" low-power-mode="20">
			<robotic-attribute-list>
				<robotic-attribute name="Strength" value="95"/>
				<robotic-attribute name="Endurance" value="95"/>
				<robotic-attribute name="Agility" value="40"/>
				<robotic-attribute name="Teaching" value="10"/>
				<robotic-attribute name="Experience Aptitude" value="95"/>
				<robotic-attribute name="Conversation" value="10"/>
			</robotic-attribute-list>
			<skill-list>
				<skill name="PSYCHOLOGY" level="1"/>
				<skill name="Medicine" level="1"/>
				<skill name="CHEMISTRY" level="1"/>
			</skill-list>
		</robot>				
		
		<robot type="ConstructionBot" make="standard"
				standby-power-consumption="0.05" fuel-consumption-rate="1" low-power-mode="20">
			<robotic-attribute-list>
				<robotic-attribute name="Strength" value="95"/>
				<robotic-attribute name="Endurance" value="95"/>
				<robotic-attribute name="Agility" value="40"/>
				<robotic-attribute name="Teaching" value="10"/>
				<robotic-attribute name="Experience Aptitude" value="95"/>
				<robotic-attribute name="Conversation" value="10"/>
			</robotic-attribute-list>
			<skill-list>
				<skill name="Construction" level="1"/>
				<skill name="AREOLOGY" level="1"/>
				<skill name="Mechanics" level="1"/>		
			</skill-list>
		</robot>
		
		<robot type="DeliveryBot" make="standard"
					standby-power-consumption="0.05" fuel-consumption-rate="1" low-power-mode="20">
			<robotic-attribute-list>
				<robotic-attribute name="Strength" value="95"/>
				<robotic-attribute name="Endurance" value="95"/>
				<robotic-attribute name="Agility" value="40"/>
				<robotic-attribute name="Teaching" value="10"/>
				<robotic-attribute name="Experience Aptitude" value="95"/>
				<robotic-attribute name="Conversation" value="10"/>
			</robotic-attribute-list>
			<skill-list>
				<skill name="Trading" level="1"/>
				<skill name="Piloting" level="1"/>
				<skill name="Mechanics" level="1"/>		
			</skill-list>
		</robot>

	</robot-list>

</robot-configuration>
